spring:
  application:
    name: HLSpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: "@123"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #níveis de log (Hierarquicos):
        #  trace -> Nível mais detalhado de log (logs infinitos)
        #  debug -> informações de depuração (fluxo e variaveis em execução)
        #  info -> funcionamento geral da aplicação
        #  warn -> eventos posivelmente problemáticas
        #  error -> erros que impedem uma execução específica
#logging:
#    file:
#      name: app.log
#    level:
#      root: warn
#management:
#  server:
#    port: 9090
#  endpoints:
#    web:
#      exposure:
#        include: '*'






