spring:
  application:
    name: HLSpringBoot
  profiles:
    active: production
# SPRING_PROFILES_ACTIVE=production
  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #níveis de log (Hierarquicos):
        #  trace -> Nível mais detalhado de log (logs infinitos)
        #  debug -> informações de depuração (fluxo e variaveis em execução)
        #  info -> funcionamento geral da aplicação
        #  warn -> eventos posivelmente problemáticas
        #  error -> erros que impedem uma execução específica



# Configurações de produção
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false

# Configurações de homologação
---
spring:
  config:
    activate:
      on-profile: homologacao
  jpa:
    show-sql: true






